// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANwtRshO1S6THK_wUXP7oyRCYXMRXf7Tw',
    appId: '1:285208110028:web:8a32145d5864558b35f369',
    messagingSenderId: '285208110028',
    projectId: 'mymeal-e5941',
    authDomain: 'mymeal-e5941.firebaseapp.com',
    databaseURL: 'https://mymeal-e5941-default-rtdb.firebaseio.com',
    storageBucket: 'mymeal-e5941.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnf7ng7gk6dSiiTA86oyI-B-iIPrS9PME',
    appId: '1:285208110028:android:d45ba02460dd7c3b35f369',
    messagingSenderId: '285208110028',
    projectId: 'mymeal-e5941',
    databaseURL: 'https://mymeal-e5941-default-rtdb.firebaseio.com',
    storageBucket: 'mymeal-e5941.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtl42rynPwY0v_ZWuOr8a4fGG-NTqE6-8',
    appId: '1:285208110028:ios:f47539750a3d715335f369',
    messagingSenderId: '285208110028',
    projectId: 'mymeal-e5941',
    databaseURL: 'https://mymeal-e5941-default-rtdb.firebaseio.com',
    storageBucket: 'mymeal-e5941.firebasestorage.app',
    iosBundleId: 'com.example.iotcw06',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtl42rynPwY0v_ZWuOr8a4fGG-NTqE6-8',
    appId: '1:285208110028:ios:f47539750a3d715335f369',
    messagingSenderId: '285208110028',
    projectId: 'mymeal-e5941',
    databaseURL: 'https://mymeal-e5941-default-rtdb.firebaseio.com',
    storageBucket: 'mymeal-e5941.firebasestorage.app',
    iosBundleId: 'com.example.iotcw06',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANwtRshO1S6THK_wUXP7oyRCYXMRXf7Tw',
    appId: '1:285208110028:web:4c4142031fa4956335f369',
    messagingSenderId: '285208110028',
    projectId: 'mymeal-e5941',
    authDomain: 'mymeal-e5941.firebaseapp.com',
    databaseURL: 'https://mymeal-e5941-default-rtdb.firebaseio.com',
    storageBucket: 'mymeal-e5941.firebasestorage.app',
  );

}